# SPDX-FileCopyrightText: © 2025 Peter Lemenkov
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["README.md", "LICENSE"]
SPDX-FileCopyrightText = "© 2025 Peter Lemenkov"
SPDX-License-Identifier = "CC0-1.0"
